name: Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-dedupe:
    runs-on: ubuntu-latest

    name: Lint & Deduplicate deps on node 10.x and ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint codebase
        run: yarn lint:post-build

      - name: Deduplicate dependencies
        run: yarn deduplicate:check

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: ['10.x', '12.x', '14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test package
        run: yarn test:post-build
